// Maximum possible score for a quiz
export const MAX_SCORE = 500;

export const POPULAR_SUBREDDITS = [
  'pics',
  'funny',
  'AskReddit',
  'gaming',
  'aww',
  'todayilearned',
  'worldnews',
  'science',
  'movies',
  'news',
  'gifs',
  'memes',
  'interestingasfuck',
  'tifu',
  'dataisbeautiful',
  'explainlikeimfive',
  'LifeProTips',
  'space',
  'sports',
  'food',
  'askscience',
  'IAmA',
  'Music',
  'books',
  'history',
  'art',
  'DIY',
  'EarthPorn',
  'OldSchoolCool',
  'nosleep',
  'Documentaries',
  'philosophy',
  'Futurology',
  'personalfinance',
  'UpliftingNews',
  'WritingPrompts',
  'GetMotivated',
  'gadgets',
  'creepy',
  'listentothis',
  'announcements',
];

export enum Screen {
  Home,
  Quiz,
  Result,
  Final,
  ScoringInfo,
}
